// Lista de estados brasileiros
export const ESTADOS_BRASIL = [
  { sigla: 'AC', nome: 'Acre' },
  { sigla: 'AL', nome: 'Alagoas' },
  { sigla: 'AP', nome: 'Amapá' },
  { sigla: 'AM', nome: 'Amazonas' },
  { sigla: 'BA', nome: 'Bahia' },
  { sigla: 'CE', nome: 'Ceará' },
  { sigla: 'DF', nome: 'Distrito Federal' },
  { sigla: 'ES', nome: 'Espírito Santo' },
  { sigla: 'GO', nome: 'Goiás' },
  { sigla: 'MA', nome: 'Maranhão' },
  { sigla: 'MT', nome: 'Mato Grosso' },
  { sigla: 'MS', nome: 'Mato Grosso do Sul' },
  { sigla: 'MG', nome: 'Minas Gerais' },
  { sigla: 'PA', nome: 'Pará' },
  { sigla: 'PB', nome: 'Paraíba' },
  { sigla: 'PR', nome: 'Paraná' },
  { sigla: 'PE', nome: 'Pernambuco' },
  { sigla: 'PI', nome: 'Piauí' },
  { sigla: 'RJ', nome: 'Rio de Janeiro' },
  { sigla: 'RN', nome: 'Rio Grande do Norte' },
  { sigla: 'RS', nome: 'Rio Grande do Sul' },
  { sigla: 'RO', nome: 'Rondônia' },
  { sigla: 'RR', nome: 'Roraima' },
  { sigla: 'SC', nome: 'Santa Catarina' },
  { sigla: 'SP', nome: 'São Paulo' },
  { sigla: 'SE', nome: 'Sergipe' },
  { sigla: 'TO', nome: 'Tocantins' },
]

// Principais cidades por estado (focando em mercado imobiliário)
export const CIDADES_POR_ESTADO: Record<string, string[]> = {
  'SP': [
    // Capital e Região Metropolitana
    'São Paulo',
    'Guarulhos',
    'Campinas',
    'São Bernardo do Campo',
    'Santo André',
    'São Caetano do Sul',
    'Diadema',
    'Mauá',
    'Ribeirão Pires',
    'Rio Grande da Serra',
    'Osasco',
    'Barueri',
    'Santana de Parnaíba',
    'Alphaville',
    'Cotia',
    'Taboão da Serra',
    'Embu das Artes',
    'Itapecerica da Serra',
    'Carapicuíba',
    'Jandira',
    'Itapevi',
    'Suzano',
    'Mogi das Cruzes',
    'Ferraz de Vasconcelos',
    'Poá',
    'Itaquaquecetuba',
    'Arujá',
    'Franco da Rocha',
    'Francisco Morato',
    'Caieiras',
    'Mairiporã',
    // Litoral
    'Santos',
    'São Vicente',
    'Praia Grande',
    'Guarujá',
    'Cubatão',
    'Bertioga',
    'Mongaguá',
    'Itanhaém',
    'Peruíbe',
    'Caraguatatuba',
    'São Sebastião',
    'Ilhabela',
    'Ubatuba',
    // Interior - Grande
    'Sorocaba',
    'Jundiaí',
    'Piracicaba',
    'Bauru',
    'São José dos Campos',
    'Ribeirão Preto',
    'São José do Rio Preto',
    'Presidente Prudente',
    'Marília',
    'Araçatuba',
    'Araraquara',
    'São Carlos',
    'Franca',
    'Limeira',
    'Taubaté',
    'Indaiatuba',
    'Americana',
    'Rio Claro',
    'Jacareí',
    'Atibaia',
    'Bragança Paulista',
    'Valinhos',
    'Vinhedo',
    'Itatiba',
    'Salto',
    'Itu',
    'Hortolândia',
    'Sumaré',
    'Paulínia',
    'Santa Bárbara d\'Oeste',
    'Botucatu',
    'Assis',
    'Ourinhos',
    'Catanduva',
    'Votuporanga',
    'Birigui',
    'Lins',
    'Jaú',
    'Barretos',
    'Bebedouro',
    'Sertãozinho',
    'Cravinhos',
    'Mococa',
    'Itapetininga',
    'Registro',
  ],
  'RJ': [
    'Rio de Janeiro',
    'São Gonçalo',
    'Duque de Caxias',
    'Nova Iguaçu',
    'Niterói',
    'Belford Roxo',
    'São João de Meriti',
    'Campos dos Goytacazes',
    'Petrópolis',
    'Volta Redonda',
    'Magé',
    'Itaboraí',
    'Mesquita',
    'Nova Friburgo',
    'Barra Mansa',
    'Macaé',
    'Cabo Frio',
    'Teresópolis',
    'Resende',
    'Nilópolis',
    'Angra dos Reis',
    'Maricá',
    'Queimados',
    'Araruama',
    'Rio das Ostras',
    'Búzios',
    'Paraty',
    'Itaguaí',
    'Japeri',
    'Guapimirim',
  ],
  'MG': [
    'Belo Horizonte',
    'Uberlândia',
    'Contagem',
    'Juiz de Fora',
    'Betim',
    'Montes Claros',
    'Ribeirão das Neves',
    'Uberaba',
    'Governador Valadares',
    'Ipatinga',
    'Sete Lagoas',
    'Divinópolis',
    'Santa Luzia',
    'Ibirité',
    'Poços de Caldas',
    'Patos de Minas',
    'Pouso Alegre',
    'Barbacena',
    'Varginha',
    'Conselheiro Lafaiete',
    'Sabará',
    'Araguari',
    'Nova Lima',
    'Passos',
    'Itabira',
    'Coronel Fabriciano',
    'Muriaé',
    'Ituiutaba',
    'Lavras',
    'São João del Rei',
    'Ouro Preto',
    'Tiradentes',
    'Diamantina',
  ],
  'RS': [
    'Porto Alegre',
    'Caxias do Sul',
    'Canoas',
    'Pelotas',
    'Santa Maria',
    'Gravataí',
    'Viamão',
    'Novo Hamburgo',
    'São Leopoldo',
    'Rio Grande',
    'Alvorada',
    'Passo Fundo',
    'Sapucaia do Sul',
    'Uruguaiana',
    'Cachoeirinha',
    'Bagé',
    'Bento Gonçalves',
    'Erechim',
    'Guaíba',
    'Cachoeira do Sul',
    'Santana do Livramento',
    'Esteio',
    'Ijuí',
    'Alegrete',
    'Santa Cruz do Sul',
    'Lajeado',
    'Torres',
    'Gramado',
    'Canela',
    'Capão da Canoa',
    'Tramandaí',
    'Xangri-lá',
  ],
  'PR': [
    'Curitiba',
    'Londrina',
    'Maringá',
    'Ponta Grossa',
    'Cascavel',
    'São José dos Pinhais',
    'Foz do Iguaçu',
    'Colombo',
    'Guarapuava',
    'Paranaguá',
    'Araucária',
    'Toledo',
    'Apucarana',
    'Pinhais',
    'Campo Largo',
    'Arapongas',
    'Almirante Tamandaré',
    'Umuarama',
    'Piraquara',
    'Cambé',
    'Fazenda Rio Grande',
    'Campo Mourão',
    'Francisco Beltrão',
    'Paranavaí',
    'Sarandi',
    'Matinhos',
    'Pontal do Paraná',
    'Guaratuba',
    'Morretes',
  ],
  'SC': [
    'Joinville',
    'Florianópolis',
    'Blumenau',
    'São José',
    'Chapecó',
    'Itajaí',
    'Criciúma',
    'Jaraguá do Sul',
    'Palhoça',
    'Lages',
    'Balneário Camboriú',
    'Brusque',
    'Tubarão',
    'São Bento do Sul',
    'Caçador',
    'Concórdia',
    'Camboriú',
    'Navegantes',
    'Rio do Sul',
    'Araranguá',
    'Biguaçu',
    'Gaspar',
    'Indaial',
    'Mafra',
    'Itapema',
    'Bombinhas',
    'Porto Belo',
    'Penha',
    'Piçarras',
    'Garopaba',
    'Imbituba',
    'Laguna',
  ],
  'BA': [
    'Salvador',
    'Feira de Santana',
    'Vitória da Conquista',
    'Camaçari',
    'Juazeiro',
    'Itabuna',
    'Lauro de Freitas',
    'Ilhéus',
    'Jequié',
    'Teixeira de Freitas',
    'Barreiras',
    'Alagoinhas',
    'Porto Seguro',
    'Simões Filho',
    'Paulo Afonso',
    'Eunápolis',
    'Santo Antônio de Jesus',
    'Valença',
    'Candeias',
    'Luís Eduardo Magalhães',
    'Mata de São João',
    'Trancoso',
    'Arraial d\'Ajuda',
  ],
  'PE': [
    'Recife',
    'Jaboatão dos Guararapes',
    'Olinda',
    'Caruaru',
    'Petrolina',
    'Paulista',
    'Cabo de Santo Agostinho',
    'Camaragibe',
    'Garanhuns',
    'Vitória de Santo Antão',
    'Igarassu',
    'São Lourenço da Mata',
    'Abreu e Lima',
    'Ipojuca',
    'Porto de Galinhas',
    'Fernando de Noronha',
  ],
  'CE': [
    'Fortaleza',
    'Caucaia',
    'Juazeiro do Norte',
    'Maracanaú',
    'Sobral',
    'Crato',
    'Itapipoca',
    'Maranguape',
    'Iguatu',
    'Quixadá',
    'Pacatuba',
    'Aquiraz',
    'Eusébio',
    'Horizonte',
    'Cascavel',
    'Beberibe',
    'Canoa Quebrada',
    'Jericoacoara',
  ],
  'GO': [
    'Goiânia',
    'Aparecida de Goiânia',
    'Anápolis',
    'Rio Verde',
    'Luziânia',
    'Águas Lindas de Goiás',
    'Valparaíso de Goiás',
    'Trindade',
    'Formosa',
    'Novo Gama',
    'Itumbiara',
    'Senador Canedo',
    'Catalão',
    'Jataí',
    'Planaltina',
    'Caldas Novas',
    'Pirenópolis',
    'Alto Paraíso de Goiás',
  ],
  'DF': [
    'Brasília',
    'Taguatinga',
    'Ceilândia',
    'Samambaia',
    'Plano Piloto',
    'Águas Claras',
    'Guará',
    'Sobradinho',
    'Planaltina',
    'Gama',
    'Santa Maria',
    'Recanto das Emas',
    'Riacho Fundo',
    'Lago Sul',
    'Lago Norte',
    'Park Way',
    'Jardim Botânico',
    'Vicente Pires',
  ],
  'PA': [
    'Belém',
    'Ananindeua',
    'Santarém',
    'Marabá',
    'Parauapebas',
    'Castanhal',
    'Abaetetuba',
    'Cametá',
    'Marituba',
    'Bragança',
    'Tucuruí',
    'Altamira',
    'Barcarena',
    'Salinópolis',
  ],
  'AM': [
    'Manaus',
    'Parintins',
    'Itacoatiara',
    'Manacapuru',
    'Coari',
    'Tefé',
    'Tabatinga',
    'Maués',
    'Iranduba',
  ],
  'MA': [
    'São Luís',
    'Imperatriz',
    'São José de Ribamar',
    'Timon',
    'Caxias',
    'Codó',
    'Paço do Lumiar',
    'Açailândia',
    'Bacabal',
    'Balsas',
    'Barreirinhas',
  ],
  'MT': [
    'Cuiabá',
    'Várzea Grande',
    'Rondonópolis',
    'Sinop',
    'Tangará da Serra',
    'Cáceres',
    'Sorriso',
    'Lucas do Rio Verde',
    'Primavera do Leste',
    'Chapada dos Guimarães',
  ],
  'MS': [
    'Campo Grande',
    'Dourados',
    'Três Lagoas',
    'Corumbá',
    'Ponta Porã',
    'Naviraí',
    'Nova Andradina',
    'Aquidauana',
    'Sidrolândia',
    'Bonito',
  ],
  'ES': [
    'Vitória',
    'Vila Velha',
    'Serra',
    'Cariacica',
    'Cachoeiro de Itapemirim',
    'Linhares',
    'São Mateus',
    'Colatina',
    'Guarapari',
    'Aracruz',
    'Viana',
    'Domingos Martins',
  ],
  'PB': [
    'João Pessoa',
    'Campina Grande',
    'Santa Rita',
    'Patos',
    'Bayeux',
    'Cabedelo',
    'Cajazeiras',
    'Conde',
  ],
  'RN': [
    'Natal',
    'Mossoró',
    'Parnamirim',
    'São Gonçalo do Amarante',
    'Macaíba',
    'Ceará-Mirim',
    'Caicó',
    'Currais Novos',
    'Tibau do Sul',
    'Pipa',
  ],
  'PI': [
    'Teresina',
    'Parnaíba',
    'Picos',
    'Piripiri',
    'Floriano',
    'Luís Correia',
  ],
  'AL': [
    'Maceió',
    'Arapiraca',
    'Rio Largo',
    'Palmeira dos Índios',
    'Penedo',
    'União dos Palmares',
    'São Miguel dos Campos',
    'Maragogi',
  ],
  'SE': [
    'Aracaju',
    'Nossa Senhora do Socorro',
    'Lagarto',
    'Itabaiana',
    'São Cristóvão',
    'Estância',
    'Barra dos Coqueiros',
  ],
  'RO': [
    'Porto Velho',
    'Ji-Paraná',
    'Ariquemes',
    'Vilhena',
    'Cacoal',
    'Rolim de Moura',
  ],
  'TO': [
    'Palmas',
    'Araguaína',
    'Gurupi',
    'Porto Nacional',
    'Paraíso do Tocantins',
  ],
  'AC': [
    'Rio Branco',
    'Cruzeiro do Sul',
    'Sena Madureira',
    'Tarauacá',
  ],
  'AP': [
    'Macapá',
    'Santana',
    'Laranjal do Jari',
    'Oiapoque',
  ],
  'RR': [
    'Boa Vista',
    'Rorainópolis',
    'Caracaraí',
  ],
}

// Cidades vizinhas/regiões estratégicas para análise de mercado
export const CIDADES_VIZINHAS: Record<string, string[]> = {
  // ABC Paulista
  'Santo André': ['São Bernardo do Campo', 'São Caetano do Sul', 'Mauá', 'Ribeirão Pires', 'Rio Grande da Serra', 'Diadema', 'São Paulo'],
  'São Bernardo do Campo': ['Santo André', 'São Caetano do Sul', 'Diadema', 'São Paulo', 'Mauá', 'Ribeirão Pires', 'Cubatão'],
  'São Caetano do Sul': ['Santo André', 'São Bernardo do Campo', 'São Paulo', 'Diadema'],
  'Diadema': ['São Paulo', 'São Bernardo do Campo', 'Santo André', 'São Caetano do Sul'],
  'Mauá': ['Santo André', 'São Bernardo do Campo', 'Ribeirão Pires', 'Suzano', 'Ferraz de Vasconcelos'],
  'Ribeirão Pires': ['Santo André', 'Mauá', 'Rio Grande da Serra', 'São Bernardo do Campo', 'Suzano'],
  'Rio Grande da Serra': ['Ribeirão Pires', 'Santo André', 'Suzano'],

  // Região Metropolitana SP
  'São Paulo': ['Guarulhos', 'Osasco', 'Taboão da Serra', 'Diadema', 'São Caetano do Sul', 'Santo André', 'São Bernardo do Campo', 'Barueri', 'Cotia'],
  'Guarulhos': ['São Paulo', 'Arujá', 'Itaquaquecetuba', 'Mairiporã'],
  'Osasco': ['São Paulo', 'Barueri', 'Carapicuíba', 'Taboão da Serra'],
  'Barueri': ['São Paulo', 'Osasco', 'Santana de Parnaíba', 'Jandira', 'Carapicuíba'],
  'Campinas': ['Valinhos', 'Vinhedo', 'Sumaré', 'Hortolândia', 'Paulínia', 'Indaiatuba', 'Americana'],

  // Litoral SP
  'Santos': ['São Vicente', 'Guarujá', 'Praia Grande', 'Cubatão'],
  'Guarujá': ['Santos', 'Bertioga', 'São Vicente'],
  'Praia Grande': ['Santos', 'São Vicente', 'Mongaguá', 'Itanhaém'],

  // Interior SP
  'Sorocaba': ['Votorantim', 'Itu', 'Salto', 'Araçoiaba da Serra', 'Mairinque'],
  'São José dos Campos': ['Jacareí', 'Caçapava', 'Taubaté', 'Pindamonhangaba'],
  'Ribeirão Preto': ['Sertãozinho', 'Cravinhos', 'Jardinópolis', 'Brodowski'],

  // Rio de Janeiro
  'Rio de Janeiro': ['Niterói', 'São Gonçalo', 'Duque de Caxias', 'Nova Iguaçu', 'Maricá'],
  'Niterói': ['Rio de Janeiro', 'São Gonçalo', 'Maricá', 'Itaboraí'],

  // Minas Gerais
  'Belo Horizonte': ['Contagem', 'Betim', 'Nova Lima', 'Santa Luzia', 'Ribeirão das Neves', 'Sabará', 'Ibirité'],

  // Sul
  'Curitiba': ['São José dos Pinhais', 'Colombo', 'Araucária', 'Pinhais', 'Campo Largo', 'Almirante Tamandaré'],
  'Porto Alegre': ['Canoas', 'Gravataí', 'Viamão', 'Alvorada', 'Cachoeirinha', 'Novo Hamburgo', 'São Leopoldo'],
  'Florianópolis': ['São José', 'Palhoça', 'Biguaçu'],
  'Balneário Camboriú': ['Itajaí', 'Camboriú', 'Navegantes', 'Itapema'],
}

// Função para buscar cidades por estado
export function getCidadesPorEstado(siglaEstado: string): string[] {
  return CIDADES_POR_ESTADO[siglaEstado] || []
}

// Função para buscar cidades vizinhas
export function getCidadesVizinhas(cidade: string): string[] {
  return CIDADES_VIZINHAS[cidade] || []
}

// Função para filtrar cidades por termo de busca
export function filtrarCidades(siglaEstado: string, termo: string): string[] {
  const cidades = getCidadesPorEstado(siglaEstado)
  if (!termo) return cidades

  const termoLower = termo.toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')

  return cidades.filter(cidade => {
    const cidadeLower = cidade.toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
    return cidadeLower.includes(termoLower)
  })
}

// Função para obter região/área metropolitana
export function getRegiaoMetropolitana(cidade: string, estado: string): string[] {
  const vizinhas = getCidadesVizinhas(cidade)
  if (vizinhas.length > 0) return vizinhas

  // Se não tem vizinhas definidas, retorna cidades do mesmo estado
  const cidadesEstado = getCidadesPorEstado(estado)
  return cidadesEstado.filter(c => c !== cidade).slice(0, 5)
}
